name: "Generate package database"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: AWFixerOS Cache
        uses: cachix/cachix-action@v12
        with:
          name: awfixeros
      - name: Create databases
        run: |
          sleep $((RANDOM % 60))
          for Line in $(cat versions)
          do
            PREV_VERSION=$(cat $Line/nixpkgs.ver)
            RUST_LOG=nix_data_generator=trace nix develop --command -- nix-data-generator -v $Line --src $Line 1>&2
            NEW_VERSION=$(cat $Line/nixpkgs.ver)
            if [ "$PREV_VERSION" != "$NEW_VERSION" ]; then
              if [ -f "$Line/nixpkgs.db" ]; then
                brotli ./$Line/nixpkgs.db -o ./$Line/nixpkgs.db.br -v -f 1>&2
              fi
              if [ -f "$Line/nixpkgs_versions.db" ]; then
                brotli ./$Line/nixpkgs_versions.db -o ./$Line/nixpkgs_versions.db.br -v -f 1>&2
              fi
            fi
          done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update databases
          commit_user_email: github-actions@github.com
          commit_author: GitHub Actions <github-actions@github.com>
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
      - name: Configure rclone for Cloudflare R2
        run: |
          mkdir -p ~/.config/rclone
          echo "[r2]" > ~/.config/rclone/rclone.conf
          echo "type = s3" >> ~/.config/rclone/rclone.conf
          echo "provider = Cloudflare" >> ~/.config/rclone/rclone.conf
          echo "access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}" >> ~/.config/rclone/rclone.conf
          echo "secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
          echo "endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com" >> ~/.config/rclone/rclone.conf
      - name: Check if cache directory exists
        id: check_cache_dir
        run: |
          if [ -d "$HOME/.cache/nix" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - name: Sync built cache to R2 using rclone
        if: steps.check_cache_dir.outputs.exists == 'true'
        run: |
          rclone sync "$HOME/.cache/nix" r2:nix-cache
