name: "Generate package database"
on:
  workflow_dispatch:
  schedule:
  - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache install Nix packages
      uses: mtoohey31/cache-flake-attrs@v2
      with:
        key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}
    - name: Create databases
      run: |
        for Line in $(cat versions)
        do
          RUST_LOG=nix_data_generator=trace nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command -- nix-data-generator -v $Line --src $Line 1>&2
          if [ -f "$Line/nixospkgs.db" ]; then
            nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command -- sqlite3 ./$Line/nixospkgs.db 'VACUUM'
            nix --extra-experimental-features nix-command --extra-experimental-features flakes develop --command -- brotli ./$Line/nixospkgs.db -o ./$Line/nixospkgs.db.br -v -f 1>&2
          fi
        done
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update databases
