name: Sync to Cloudflare R2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to R2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync to R2
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: r2 sync $PWD nix-cache
