name: Sync to Cloudflare R2

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to R2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ github.workspace/nix-cache }}

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
      - name: Configure rclone for Cloudflare R2
        run: |
          mkdir -p ~/.config/rclone
          echo "[r2]" > ~/.config/rclone/rclone.conf
          echo "type = s3" >> ~/.config/rclone/rclone.conf
          echo "provider = Cloudflare" >> ~/.config/rclone/rclone.conf
          echo "access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}" >> ~/.config/rclone/rclone.conf
          echo "secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}" >> ~/.config/rclone/rclone.conf
          echo "endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com" >> ~/.config/rclone/rclone.conf
          - name: Check if nix-cache directory exists
            run: |
              if [ ! -d "$GITHUB_WORKSPACE/nix-cache" ]; then
                echo "Directory $GITHUB_WORKSPACE/nix-cache does not exist. Skipping sync."
                exit 0
              fi
          - name: Sync to R2 using rsync-like rclone
            if: exists('${{ github.workspace }}/nix-cache')
            run: |
              rclone sync "$GITHUB_WORKSPACE/nix-cache r2:nix-cache
